# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "115acb7a6e1f79401785d5c048f41703"
name = "represent-translate"
handle = "auto-translate-1"
application_url = "https://aol-ham-default-seems.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-ed0d1b63.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://aol-ham-default-seems.trycloudflare.com/auth/callback",
  "https://aol-ham-default-seems.trycloudflare.com/auth/shopify/callback",
  "https://aol-ham-default-seems.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
